# Generated by Django 4.2.3 on 2023-07-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_location_partcipant_meetup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default=32, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
